### ISSUE TITLE
How do you view this paper?

### ISSUE THREAD

**Issue by jzhang38** [thunlp/UltraChat#13]
https://huggingface.co/papers/2305.15717

**Comment by dingn42** [comment]
> https://huggingface.co/papers/2305.15717

Thanks! It is a very interesting paper, we agree on some of the points, but we have also observed different conclusions in our models. We will update when our evaluations are all completed!

**Comment by jzhang38** [comment]
Thanks! That's great to hear. Eager waiting for the update!
