### ISSUE TITLE
Question about this figure: https://github.com/thunlp/UltraChat#our-evaluation-set

### ISSUE THREAD

**Issue by zhisbug** [thunlp/UltraChat#16]
Does this figure (https://github.com/thunlp/UltraChat#our-evaluation-set) suggest that: 
Vicuan-13B < WizardLM-13B < Koala-13B < ... < Dolly-12B on our extended GPT-4 based benchmark?

This seems to deviate from all existing leaderboard results and conclusions. Could you explain?

**Comment by dingn42** [comment]
> Does this figure (https://github.com/thunlp/UltraChat#our-evaluation-set) suggest that: Vicuan-13B < WizardLM-13B < Koala-13B < ... < Dolly-12B on our extended GPT-4 based benchmark?
> 
> This seems to deviate from all existing leaderboard results and conclusions. Could you explain?

Thanks for the comment. The figure actually suggests the other way: Vicuan-13B > WizardLM-13B > Koala-13B > ... > Dolly-12B. If you mean that the performance of Vicuna and WizardLM differs from the leaderboard, it may be because our evaluation emphasizes correctness rather than other factors.

**Comment by zhisbug** [comment]
@ningding97 oh thanks, now I understand the win rate in the figure means ChatGPT wins over other models, right?

**Comment by dingn42** [comment]
> @ningding97 oh thanks, now I understand the win rate in the figure means ChatGPT wins over other models, right?

The win rate is UltraLM vs Other models. 😁
