### ISSUE TITLE
关于模型产出乱码的问题

### ISSUE THREAD

**Issue by xuxinzhang** [thunlp/UltraChat#24]
麻烦大佬帮忙看看这个问题，sh chat_cli.sh后模型的回答疑似乱码：Assistant: locatelausften确rareрис anim Mandlandorandäscontrastic doit ancestló translateamsungome Accept My---сковbraenigMAINateur希 Diese visinqqTasks Wu\}$.laus fat�ā`, blancовин Ontario Pow Zahlutter}>ieldood House Heaven Vincentlimpсторill average：=' PhiladelSer dut papaNew  deriv

**Comment by dingn42** [comment]
> 麻烦大佬帮忙看看这个问题，sh chat_cli.sh后模型的回答疑似乱码：Assistant: locatelausften确rareрис anim Mandlandorandäscontrastic doit ancestló translateamsungome Accept My---сковbraenigMAINateur希 Diese visinqqTasks Wu\}$.laus fat�ā`, blancовин Ontario Pow Zahlutter}>ieldood House Heaven Vincentlimpсторill average：=' PhiladelSer dut papaNew  deriv

您好！感谢关注，不出意外您应该是直接使用了 Delta Weights 来进行推理。根据 Llama 官方要求，必须将 Delta weights 和官方 weight合并之后才能正常使用

**Comment by xuxinzhang** [comment]
感谢🙏，我试下
