### ISSUE TITLE
Training a new SOTA foundation model

### ISSUE THREAD

**Issue by Alignment-Lab-AI** [thunlp/UltraChat#3]
hello! im training a new model with a unique architecture designed to work in my project (https://github.com/webgrip/CogniSwarm) 

i just wanted to be sure if it was ok to use your dataset in my training. i read the license information but a lot of it went over my head - would this use be in scope?

**Comment by dingn42** [comment]
> 

Yes! it's gonna be OK if you use the data for non-commercial use.
