### ISSUE TITLE
TEMPLATE = "{}\n\n### Assistant:" Can Create future problem like Vicuna

### ISSUE THREAD

**Issue by Ejafa** [thunlp/UltraChat#6]
[NOTE: Weights v1.1 are only compatible with transformers>=4.28.0 and fschat >= 0.2.0. Please update your local packages accordingly. If you follow the above commands to do a fresh install, then you should get all the correct versions](https://github.com/lm-sys/FastChat)

To Fit the compatibility issues of LlamaTokenizer, The Project Had to update weights again.
For Future work, SFT on TEMPLATE = "{}\n\n### Assistant:", can create problem

**Comment by yulinchen99** [comment]
Thx for reminding, we have fixed that.
